# Generated by Django 5.1.7 on 2025-03-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shipcategory_ship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shipcategory',
            options={'managed': False},
        ),
    ]
