# Generated by Django 5.1.7 on 2025-03-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ship_options_alter_shipcategory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ship',
            table='ships',
        ),
        migrations.AlterModelTable(
            name='shipcategory',
            table='ship_categories',
        ),
    ]
