# Generated by Django 5.1.7 on 2025-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pedido_nave_delete_nave'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
