# Generated by Django 5.1.7 on 2025-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eveprofile_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eveprofile',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
